### ISSUE TITLE
Test jobs failed with error "[ERROR] Could not initialize class com.zebrunner.agent.core.config.ConfigurationHolder"

### ISSUE THREAD

**Issue by okamara** [zebrunner/jenkins-master#379] opened 2023-03-17 16:22 UTC
Steps:
1.Set up community edition (developer branch)
Note:Used Carina-demo (master)
2.Start Api and Web test jobs
Actual result: test job failed with error [ERROR] Could not initialize class com.zebrunner.agent.core.config.ConfigurationHolder
Expected: Api and Web test jobs passed

**Comment by okamara** [comment] 2023-03-21 08:59
This issue is repro here
http://3.126.150.168/jenkins/job/okamara/job/carina-demo/job/API-Demo-Test/1/console
for repo -> https://github.com/okamara/carina-demo.git

**Comment by vdelendik** [comment] 2023-04-23 12:03
closed as can't reproduce anymore. potentially issue occurred due to the carina updates

**Closed by vdelendik** 2023-04-23 12:03 UTC
Labels: bug
